version: '3.1'

services:

  voipmonitor-sniffer:
    container_name: voipmonitor-sniffer
    image: qxip/voipmonitor-hep
    network_mode: "host"
    restart: always
    volumes:
      - ./voipmonitor:/var/spool/voipmonitor
